#!/usr/bin/env python3

import subprocess
import json
import time


# The display that is already rotating automatically
PRIMARY = "eDP-1"

# The display you want to sync
SECONDARY = "eDP-2"

# Screen dimensions
WIDTH = 2880
HEIGHT = 1800

rotation_name_map = {
    1: "normal",
    2: "left",
    4: "inverted",
    8: "right",
}

while True:
    # Get display 1's rotation
    doctor_output = json.loads(subprocess.check_output(["kscreen-doctor", "-j"]))
    output_1_rotation = None
    output_2_rotation = None
    output_1_position = None
    output_2_position = None
    output_1_scale = None
    output_2_scale = None
    for output in doctor_output["outputs"]:
        if output["name"] == PRIMARY:
            output_1_rotation = rotation_name_map[output["rotation"]]
            output_1_scale = output["scale"]
            output_1_position = f"{output["pos"]["x"]},{output["pos"]["y"]}"
        elif output["name"] == SECONDARY:
            output_2_rotation = rotation_name_map[output["rotation"]]
            output_2_scale = output["scale"]
            output_2_position = f"{output["pos"]["x"]},{output["pos"]["y"]}"

    if output_1_rotation is None:
        print(f"Warning: Could not find rotation for display {PRIMARY}")
        time.sleep(10)
        continue
    if output_1_scale is None or output_2_scale is None:
        print(f"Warning: Could not find display scales")
        time.sleep(10)
        continue

    # Apply it to display 2. Note that display 1 is physically upside down.
    if output_1_rotation == "normal":
        # Machine is upside down
        output_1_new_position = f"0,{int(HEIGHT/output_2_scale)}"
        output_2_new_position = "0,0"
        output_2_new_rotation = "inverted"
    elif output_1_rotation == "right":
        # Machine is on its right edge
        output_1_new_position = f"{int(HEIGHT/output_1_scale)},0"
        output_2_new_position = "0,0"
        output_2_new_rotation = "left"
    elif output_1_rotation == "left":
        # Machine is on its left edge
        output_1_new_position = "0,0"
        output_2_new_position = f"{int(HEIGHT/output_1_scale)},0"
        output_2_new_rotation = "right"
    else:
        # Machine is upright.
        output_1_new_position = "0,0"
        output_2_new_position = f"0,{int(HEIGHT/output_1_scale)}"
        output_2_new_rotation = "normal"
    if output_2_rotation != output_2_new_rotation:
        subprocess.check_call(
            [
                "kscreen-doctor",
                f"output.{SECONDARY}.rotation.{output_2_new_rotation}",
            ]
        )
    if output_1_new_position != output_1_position:
        subprocess.check_call(
            [
                "kscreen-doctor",
                f"output.{PRIMARY}.position.{output_1_new_position}",
            ]
        )
    if output_2_new_position != output_2_position:
        subprocess.check_call(
            [
                "kscreen-doctor",
                f"output.{SECONDARY}.position.{output_2_new_position}",
            ]
        )
    time.sleep(1)
